import type { CatalogObject } from "./catalog-object";
import { TBD_OWNER_SLOT } from "./catalog-object";

const businessMetricsAgentRef = {
  id: "agent-business-metrics",
  type: "domain_agent",
  name: "业务指标 Agent",
} as const;

export const catalogSeedObjects: CatalogObject[] = [
  {
    id: "workflow-ai-conversion",
    type: "workflow",
    name: "AI+ 转化分析流程",
    slug: "ai-conversion-workflow",
    purpose: "按固定节奏生成 AI+ 转化表现分析，并把异常指标交给领域 Agent 归因。",
    ownerSlot: { status: "assigned", name: "小助", team: "增长" },
    inputs: ["BI 指标", "星图链路数据", "投放活动信息"],
    outputs: ["经营简报", "异常指标列表", "后续跟进行动"],
    trigger: "每日 10:00 定时触发",
    permission: "只读访问 BI 与星图数据，需要发送结果到钉钉群。",
    eval: "指标口径正确、异常识别有效、输出可追溯。",
    lifecycle: "pilot",
    tags: ["经营节奏", "conversion", "daily"],
    dependencies: [businessMetricsAgentRef],
    usedBy: [],
    description: "第一条运营类固定工作流样板，用来验证 Workflow 调用 Domain Agent 的闭环。",
  },
  {
    id: "agent-business-metrics",
    type: "domain_agent",
    name: "业务指标 Agent",
    slug: "business-metrics-agent",
    purpose: "统一业务指标口径，监控目标进展和异常波动，给出归因、影响面和下一步建议。",
    ownerSlot: { status: "assigned", name: "小助", team: "业务运营" },
    inputs: ["指标定义", "BI 查询结果", "历史波动记录"],
    outputs: ["指标解释", "异常归因", "经营建议"],
    trigger: "被 Workflow 或个人入口按需调用",
    permission: "读取指标和看板数据，不直接修改业务系统。",
    eval: "口径正确、证据充分、建议可行动。",
    lifecycle: "review",
    tags: ["business", "metrics", "domain-agent"],
    dependencies: [],
    usedBy: [{ id: "workflow-ai-conversion", type: "workflow", name: "AI+ 转化分析流程" }],
    description: "第一批领域判断对象，负责业务口径和转化波动解释。",
  },
  {
    id: "skill-link-inspect",
    type: "skill",
    name: "aetheris-link-inspect",
    slug: "aetheris-link-inspect",
    purpose: "复用 Aetheris CLI 检查业务链接、活动参数和落地页基础信息。",
    ownerSlot: TBD_OWNER_SLOT,
    inputs: ["业务链接", "活动上下文"],
    outputs: ["链接解析结果", "参数风险", "可读摘要"],
    trigger: "被 Workflow、Domain Agent 或 Bug 修复流程调用",
    permission: "需要调用 Aetheris CLI，只读解析链接。",
    eval: "解析稳定、异常参数识别准确。",
    lifecycle: "draft",
    tags: ["skill", "aetheris", "link"],
    dependencies: [{ id: "tool-aetheris-cli", type: "tool", name: "Aetheris CLI" }],
    usedBy: [{ id: "workflow-ai-conversion", type: "workflow", name: "AI+ 转化分析流程" }],
    description: "Skill 作为一等对象进入 Catalog，后续再接测试、版本和 worker 同步。",
  },
  {
    id: "worker-openclaw-m1",
    type: "worker",
    name: "OpenClaw M1 Worker",
    slug: "openclaw-m1-worker",
    purpose: "承载本地 OpenClaw 任务执行、Skill Dry Run 和浏览器类任务。",
    ownerSlot: { status: "assigned", name: "卷柏", team: "研发基础设施" },
    inputs: ["Task Queue 任务", "Skill 执行请求"],
    outputs: ["执行日志", "任务产物", "健康状态"],
    trigger: "Runtime Fabric 分配任务",
    permission: "仅执行已授权任务，外部凭证由执行环境隔离。",
    eval: "heartbeat 正常、任务执行成功、失败日志可追溯。",
    lifecycle: "monitor",
    tags: ["worker", "runtime", "m1"],
    dependencies: [],
    usedBy: [],
    description: "第一批多设备执行对象，先用于验证 Worker Fleet 和 Run Trace 的数据表达。",
  },
  {
    id: "tool-aetheris-cli",
    type: "tool",
    name: "Aetheris CLI",
    slug: "aetheris-cli",
    purpose: "提供命令行能力，用于链接检查、项目查询和研发工作辅助。",
    ownerSlot: { status: "assigned", name: "卷柏", team: "研发基础设施" },
    inputs: ["命令参数", "项目上下文"],
    outputs: ["命令输出", "结构化摘要"],
    trigger: "被 Skill 或 Agent 调用",
    permission: "按命令能力分配 scope，默认不允许破坏性操作。",
    eval: "命令可复现、输出可解析、失败原因清楚。",
    lifecycle: "production",
    tags: ["tool", "cli", "aetheris"],
    dependencies: [],
    usedBy: [{ id: "skill-link-inspect", type: "skill", name: "aetheris-link-inspect" }],
    description: "工具对象只描述能力边界，不承载领域判断。",
  },
  {
    id: "data-bi-metrics",
    type: "data_source",
    name: "BI 指标数据源",
    slug: "bi-metrics-data-source",
    purpose: "为业务指标、成本效率和质量分析提供事实数据与指标口径。",
    ownerSlot: { status: "assigned", name: "昭扬", team: "数据" },
    inputs: ["查询条件", "指标口径"],
    outputs: ["指标结果", "时间序列", "分组维度"],
    trigger: "被 Workflow、Domain Agent 或 Skill 查询",
    permission: "只读查询，敏感维度需要额外审批。",
    eval: "数据新鲜、口径稳定、查询失败可定位。",
    lifecycle: "production",
    tags: ["data", "bi", "metrics"],
    dependencies: [],
    usedBy: [businessMetricsAgentRef],
    description: "第一版 Catalog 只展示数据源边界，不实现连接配置。",
  },
  {
    id: "memory-decision",
    type: "memory",
    name: "决策记忆",
    slug: "decision-memory",
    purpose: "沉淀关键判断、复盘结论和策略变化，供后续 Agent 与 Workflow 引用。",
    ownerSlot: TBD_OWNER_SLOT,
    inputs: ["Decision Record", "复盘结论", "策略变更"],
    outputs: ["可引用决策上下文", "历史判断依据"],
    trigger: "Run 完成或 Governance 审计后写入",
    permission: "写入需要来源和 owner，读取按项目范围控制。",
    eval: "来源清晰、引用准确、过期内容可发现。",
    lifecycle: "draft",
    tags: ["memory", "decision"],
    dependencies: [],
    usedBy: [],
    description: "记忆对象先作为 Catalog 元数据存在，后续再接 Memory Governance。",
  },
  {
    id: "policy-cost-guard",
    type: "policy",
    name: "成本守护策略",
    slug: "cost-guard-policy",
    purpose: "约束模型、工具和 Worker 消耗，发现异常成本并触发提醒或审批。",
    ownerSlot: TBD_OWNER_SLOT,
    inputs: ["运行成本", "预算边界", "对象 owner"],
    outputs: ["成本风险信号", "审批要求", "治理记录"],
    trigger: "Run 执行中和执行后检查",
    permission: "可读取成本数据，可触发审批，不自动中断生产任务。",
    eval: "异常召回有效、误报可控、owner 可追溯。",
    lifecycle: "review",
    tags: ["policy", "cost", "governance"],
    dependencies: [],
    usedBy: [businessMetricsAgentRef],
    description: "Governance 的第一批策略对象之一，用来验证风险信号在 Catalog 中的表达。",
  },
];
